#!/bin/sh
# lcl: Latex CLean, clean intermediate files in current (sub)directory when building pdf from tex



clean(){
    files=$(find . -type f -regextype egrep -regex ".*\.(aux|log|fls|synctex\.gz|fdb_latexmk)")
    array=($files)

    if [[ ${#array[@]} -eq 0 ]]
    then
        echo "Already clean"
        return
    fi

    for file in ${array[@]}
    do
        rm ${file}
    done 

    echo "Latex intermediate files cleaned"

}

clean
